### ISSUE TITLE
Prise en charge des relations n-n

### ISSUE THREAD

**Issue by alhyss** [cnigfr/structuration-reglement-urbanisme#1]
... entre les fragments du règlement d'un côté, et les enregistrements de la table des prescriptions de l'autre.

J'ouvre cette issue pour confirmer le mécanisme et discuter de ses implications.

Si je comprends bien la nouvelle version du manuel d'utilisation, les relations n-n sont gérées côté règlement, où l'attribut `idPrescription` (et les `idPresc`, `idPrescStart` et `idPrescEnd` servant à sa saisie) admettent des listes d'identifiants, qui sont en quelque sorte la clé primaire d'une table pivot implicite.

Prenons l'exemple des immeubles protégés du PSMV du Marais, à Paris. Dans ce PSMV, on a la partie US.11A qui définit (1) les règles applicables à la fois aux immeubles de type A et de type B ([page 36](https://cdn.paris.fr/paris/2020/02/26/231c8fcc289ecfb8462074c893c2eb71.pdf#page=36)), avec (2) quelques paragraphes qui ne sont applicables qu'aux immeubles de type A (comme l'encadré en haut de la [page 47](https://cdn.paris.fr/paris/2020/02/26/231c8fcc289ecfb8462074c893c2eb71.pdf#page=47)). Il y a aussi (3) des dispositions portant sur le bâti protégé qui sont disséminées dans d'autres parties du règlement (comme le point 5 en bas de la [page 72](https://cdn.paris.fr/paris/2020/02/26/231c8fcc289ecfb8462074c893c2eb71.pdf#page=72)).

Si je comprends bien :
- côté table des prescriptions, on associerait simplement la nature `"type_a"` aux enregistrements correspondant au bâti de type A et la nature `"type_b"` pour ceux de type B ;
- côté règlement, pour (1) et (3) on placerait des balises `Contenu` avec l'attribut `idPrescription` valant `"07-50-type_a,07-50-type_b"`, et pour (2) on placerait des balises `Contenu` avec `idPrescription` valant juste `"07-50-type_a"`.

Vous confirmez que ça fonctionne de cette façon ?

Je saisis mieux maintenant pourquoi le nouveau champ `nature` s'appellerait ainsi. Ce n'est pas un identifiant, contrairement à ce que je disais à la réunion d'hier, c'est une sous-catégorisation servant de troisième composante à un identifiant qui est en fait formé du code, du sous-code et de la nature.

**Comment by alisonlenain** [comment]
Clément Bouché confirme qu’il Il s'agit d'une bien d'une sous-catégorisation optionnelle qui vient "spécialisé" la catégorie existante : 07-50-type_a ; 07-50-type_b. Elles respectent toutes les deux les règles générale de 07-50. Cette sous-catégorisation permettra de retrouver la sous partie exacte du règlement. C'est un complément d'adresse et non pas un identifiant.

**Comment by alhyss** [comment]
@alisonlenain Merci à tous les deux pour cette confirmation !
