### ISSUE TITLE
Code SIREN pour les PLUi

### ISSUE THREAD

**Issue by nkulpinski** [cnigfr/structuration-reglement-urbanisme#10]
Dans le cadre de la saisie des communes pour le cas d'un PLUi il serait plus pertinent de ne saisir que le code SIREN de la collectivité avec son sous-code lettre à la place de la liste des codes INSEE des communes impactées.

Merci

**Comment by nkulpinski** [comment]
La liste des communes impactée reste toutefois pertinente

**Comment by alisonlenain** [comment]
Code SIREN intégré à l'outil web
