### ISSUE TITLE
Remarques sur le catalogue d'objets vprojet_2023-11_Retrait / Alignement / RetraitFaçadeHauteur

### ISSUE THREAD

**Issue by ynakhimo** [cnigfr/structuration-reglement-urbanisme#16]
## Classes Retrait / Alignement / RetraitFaçadeHauteur
- Si on veut définir un alignement obligatoire sur la limite publique, est-ce qu’on a besoin de définir a) retrait = 0 b) _alignementAutorise_ = oui dans la classe Alignement (ça semble un peu alambiqué), et comment indiquer la limite de référence ?
- Pourquoi est-ce que l’énumération _typeRetrait_ comprend des valeurs aussi différentes que _minimum_ et _parRapport_ ?
- Pourquoi est-ce que la valeur de _retraitMin_ est un pourcentage ? Comment indiquer un retrait qui dépende de la hauteur façade ? Un retrait mesuré au centre de la façade ?
- Comment indiquer un alignement obligatoire sur au moins ou au plus une bordure ou d’une latérale à l’autre pour une règle d’article 7 ?

**Comment by GT-CNIG-DDU** [comment]
> Comment définir un alignement obligatoire sur la limite publique ?

Je suppose qu'il faut créer un objet `Alignement` et un objet `RetraitAlignement` avec reference = "emprise publique".
Comme la classe `Alignement` ne comprend pas d'attribut, on s'interroge effectivement sur sa fonction...
@alisonlenain se pose la même question en commentaire dans le projet de standard.

> Pourquoi est-ce que l’énumération _typeRetrait_ comprend des valeurs aussi différentes que _minimum_ et _parRapport_ ?

=> La valeur "parRapport" n'a effectivement pas lieu d'être puisque la référence est indiquée dans la classe `RetraitAlignement`

> Pourquoi est-ce que la valeur de _retraitMin_ est un pourcentage ?

erreur de copié-collé probablement
=> à corriger

> Comment indiquer un retrait qui dépende de la hauteur façade ?

Le projet de standard indique _"Ce retrait se fait suivant un prospect défini par une pente et un recul minimal."_
=> Effectivement : définir la formule permettant de calculer le retrait à partir de la pente et du recul minimal.

**Comment by ynakhimo** [comment]
La suite de la réflexion.
(1) Pour moi il y a besoin de définir 4 règles principales : 
- **A** alignement obligatoire (qui peut être partiel et avoir d'autres attributs tels que "bâtiments de 2nd rang non acceptés (_booléen_)")
- **Rmin** retrait minimal obligatoire (où il faut indiquer une valeur de retrait)
- **Rmax** retrait maximal (qui peut avoir deux valeurs : minimale et maximale, et doit en avoir au moins la deuxième)
- **AouR** alignement ou retrait minimal (où il faut indiquer une valeur de retrait et, au choix, une obligation d'implantation sur au moins/au plus N limites (parmi la liste de référence))

On pourrait donc opter pour : 
- une seule classe **RetraitAlignement** qui définit la règle principale d'implantation vis-à-vis de bordures,
- au moins trois (sous-)classes distinctes qui représentent les règles **A**, **R**, **AouR**,
- ajout d'un attribut *depuis au moins / au plus X limites* dans la classe **Alignement** (et, au choix, dans la classe **Retrait** également) et convenir que si les deux classes sont utilisées dans la même contrainte, il s'agit d'une **AouR** et sinon d'une des règles obligatoires,
- les règles d'implantation scindées en deux : une sous-classe qui regroupe les contraintes d'article 6 (vis-à-vis des limites publiques) et une autre pour l'article 7 (vis-à-vis des limites séparatives), puisque ni les règles en soi ni le calcul géométrique en soi ne sont pas à 100% identiques pour les deux types de limite.
___
(2) Tout comme dans le cas du champ d'application, on aura besoin de faire le lien avec la VoirieBordante.
___
(3) On n'a pas encore abordé la notion d'héberges. Encore une fois, elle ne sera pas tout à fait pareil en articles 6, 7 et 10, mais globalement elle représente : 
- soit la possibilité de déroger à la contrainte indiquée en s'inscrivant dans les héberges horizontales et/ou verticales (ou, dans le cas de l'article 6, en prolongeant les façades) des bâtiments voisins
- soit l'obligation de se faire (sous condition de la présence desdits bâtiments voisins contigus (ou pas, dans le cas de l'article 6))

**Comment by GT-CNIG-DDU** [comment]
Concernant le (2), ce lien peut être matérialisé par la relation "`RetraitAlignement` _est induit par_ `Voiriebordante`" en ajoutant un attribut RetraitAlignement.`voirieBordante` contenant (le cas échéant, c'est donc un remplissage facultatif) la valeur de l'identifiant `VoirieBordante.Id`

@alisonlenain : s'assurer que toutes les classes d'objets disposent bien d'un attribut ID (=> projet de standard à corriger dans ce sens)

**Comment by alisonlenain** [comment]
L'ensemble de classes contiennent bien un ID hérité de l'une des classes ContraintesUnitaires , ConditionUnitaires. 
Proposition lors de la dernière réunion de supprimer la classe "RetraitAlignement" et d'ajouter l'attribut Reference : TypeReference dans les trois classes : Alignement, Retrait et RetraitFaçade.

Autre Proposition de modelisation de Buildzr dans les commentaires : question à trancher lors de la prochaine réunion SG6 : 08/03

**Comment by GT-CNIG-DDU** [comment]
> L'ensemble de classes contiennent bien un ID hérité de l'une des classes ContraintesUnitaires , ConditionUnitaires.

Oui, bien sûr. Le propos est de s'assurer que dans le projet de standard SRU2 chaque classe contient bien l'attribut Id_<classe> dans la description la classe.

**Comment by mbrasebin** [comment]
Je suis plutôt favorable au choix d'avoir 3 classes pour que les 3 concepts soient explicités par l'intitulé de la classe (en termes de modélisation, ça ne change rien dans le fond)

**Comment by alisonlenain** [comment]
Conservation des classes distinctes. 

Proposition d'ajout dans la classe Retrait (proposition Buildrz) : 

-  attributs Rmin retrait minimal obligatoire (où il faut indiquer une valeur de retrait)
- Rmax retrait maximal (qui peut avoir deux valeurs : minimale et maximale, et doit en avoir au moins la deuxième)
- AouR alignement ou retrait minimal (où il faut indiquer une valeur de retrait et, au choix, une obligation d'implantation sur au moins/au plus N limites (parmi la liste de référence))


Nécessité de préciser si "distance" dans la classe Retrait, s'il s'agit d'une distance maximale ou minimale, ou bien les deux. (Soit création deux attributs soit un dataType avec valeur maximale et minimale).

Remarque du projet PPP : Proposition d’ajout de l’attribut distanceAlternative permettra pour préciser une méthode particulière de mesure, présente à de nombreuses reprises dans le PLU de Pechbonnieu.

**Comment by alisonlenain** [comment]
Déplacement de l’attribut Alignement dans la classe Alignement liée à l’énumération et aux valeurs (autorise, impose, interdit)

Revoir les liens d'héritages entre les classes Retrait, RetraitAlignement, Alignement, RetraitFaçadeHauteur. 

Duplication dans les informations dans la classe Retrait : Rmin et Rmax sont présents en tant qu’attribut de le classe Retrait et également en tant que valeurs énumérée dans « TypeRetrait ». Proposition de supprimer cet attribut Type et l’énumération « TypeRetrait » et d’ajout un attribut « retraitParRapport » avec type de donnée characterString qui laissera une plus grande flexibilité à l’utilisateur pour renseigner ces informations (pouvant définir par rapport à une ou plusieurs limites).

**Comment by alisonlenain** [comment]
Nécessité de rajouter un attribut "profondeurConstructions" (se mesure sur la largeur et non la longeur de tout poiny de la façade avant et le point de la façade arrière qui lui est opposé) ?
Exemple provenant du PLUI de Marseille.

**Comment by alisonlenain** [comment]
Déplacement de l’attribut "alignement" dans la classe Alignement avec l’énumération "TypeAlignement" et les valeurs (autorise, impose, interdit)

**Comment by GT-CNIG-DDU** [comment]
Sauf erreur de ma part, dans le projet de standard ce serait plutôt l’attribut "nature" dans la classe Alignement avec l’énumération "TypeAlignement" et les valeurs (autorise, impose, interdit).

**Comment by alisonlenain** [comment]
C'est ce qui a été inscrit dans le document du standard SRU niveau 2. Se référer au document du standard envoyé

**Comment by GT-CNIG-DDU** [comment]
Une question : 
Dans le chainage des trois classes "Retrait", "RetraitAlignement" et "Alignement", "Alignement" hérite bien des attributs de la classe "Retrait" (libellé, type, commentaire) mais pas de l'attribut (reference) de la classe intermédiaire "RetraitAlignement" ?

**Comment by alisonlenain** [comment]
la classe Alignement hérite de la classe RetraitAlignement. 
La classe RetraitAlignement hérite des attributs de la classe Contrainte ( id, libelle, type et commentaire).
La classe  Alignement hérite des attributs id et reference de la classe RetraitAlignement.

![image](https://github.com/user-attachments/assets/bf77a2b9-83df-4c4a-9f09-a584ba25d211)

**Comment by GT-CNIG-DDU** [comment]
Oui, je suis d'accord mais : 
- il faut ajouter l'attribut reference à la liste d'attributs des classes "alignement" (page 29) et "retrait" (page 30) et "RetraitFacadeHuteur" (page 31)
- la classe contrainte est mal nommée dans le projet de standard (elle y est nommée "retrait") : 

![image](https://github.com/user-attachments/assets/878b3dcb-6a27-4e18-afec-4590cf7d6696)

**Comment by alisonlenain** [comment]
Ok pour rajouter l'attribut référence à la liste d'attributs des classes "alignement" (page 29) et "retrait" (page 30) et "RetraitFacadeHuteur" (page 31). 

Oui, j'avais vu cette erreur dans le diagramme UML. J'ai corrigé ça dans la dernière version du document de standard que j'ai déposé sur le Github

**Comment by alisonlenain** [comment]
Suppression de l'attribut "distance" dans la classe Retrait car l'information est représentée par les attributs "rMin" , "rMax" et "parRapport".
