### ISSUE TITLE
Forme des valeurs de `nature`

### ISSUE THREAD

**Issue by alhyss** [cnigfr/structuration-reglement-urbanisme#2]
*Valeurs du futur champ `nature` de la table des prescriptions et troisième composante de l'attribut `idPrescription` des éléments  `Titre` et `Contenu` dans le XML du règlement.*

La nécessité de permettre des valeurs de `nature` composées de plusieurs mots a été évoquée hier, avec pour solution le fait d'autoriser les tirets bas `"_"`.

Est-ce que permettre l'emploi de majuscules pourrait également être une option ? Dans l'exemple que je citais dans le ticket #1, `"typeA"` et `"typeB"` auraient pu avantageusement remplacer `"type_a"` et `"type_b"`. Ou y a-t-il une raison à l'interdiction des majuscules ?

J'ai aussi tendance à penser que la limite de longueur, même étendue à 20 caractères, reste inutilement stricte. S'il n'y a pas de motif technique (y en a-t-il ?), alors monter jusqu'à 50 caractères ne me paraîtrait pas choquant et autoriserait des noms plus explicites. Pour qu'on puisse écrire des choses comme `"recul_par_rapport_a_la_voie"` (ou `"reculParRapportALaVoie"`) plutôt que `"recul_voie"`, par exemple.

**Comment by alisonlenain** [comment]
Il n'y a pas de raison technique de limité le champ en taille. Voici les contraintes préconisées : 
-	Champs texte de 255 caractères maximum (limite suffisante et cohérente avec une montée en base de données).
-	Sans espace, sans accentuation, sans caractères spécial.
-	Les minuscules et majuscules sont acceptées.

**Comment by alhyss** [comment]
D'accord avec ça. S'il n'y a pas de volonté d'homogénéisation des valeurs au niveau national, alors autant rester souples et laisser à chacun la possibilité de s'adapter à ses propres contraintes.

Est-ce que les tirets hauts seraient acceptés, étant donné qu'ils servent déjà de séparateurs entre les trois composantes des `idPrescription` ? Je pense que ça mériterait d'être explicité, considérant qu'ils ne sont généralement pas perçus comme des caractères spéciaux.

**Comment by alisonlenain** [comment]
Oui, les tirets du hauts sont acceptés

**Comment by GT-CNIG-DDU** [comment]
1 Je suis d'accord avec un champ étendu à 50 caractères
Aller au delà me semblerait être un mauvais signal donné aux collectivités dans la mesure où cette correspondance doit s'établir sur un libellé générique, donc nécessairement court pour assurer justement ce caractère de généricité.

2/ Dans l'actuelle version du standard (sa version littérale) il ne me semble pas que l'emploi des majuscules soit proscrit, en reprenant l'exemple cité : on peut tout à fait envisager <TYPEPSC>-<STYPEPSC>-type_A (resp. type_B).
J'ai demandé à Alison d'ajouter des exemples textuels pour NATURE dans le projet de standard.

N'étant pas familier avec le format, je n'ai pas encore lu le xsd. Leslie qu'est-ce qui selon toi empêche les majuscules, est-ce le xsd ?

**Comment by alhyss** [comment]
@GT-CNIG-DDU Rien n'empêche les majuscules à ma connaissance. Au contraire, je trouvais dommage de les interdire, comme c'était le cas dans la proposition initiale (du moins dans la présentation au SG6, je ne sais plus si cette règle a jamais figuré dans le standard).

**Comment by alisonlenain** [comment]
Bonjour, 
Dans les recommandations faites par Clément Bouché, il a été précisé que les majuscules été acceptées. Cette précision a également été intégrée dans le CR du 16/12.
