### ISSUE TITLE
[PPP ESGT] Suggestions d'améliorations du MCD - Proposition de modification des classes Autorisation et Interdiction

### ISSUE THREAD

**Issue by Elise-DELACOTTE** [cnigfr/structuration-reglement-urbanisme#22]
Nous proposons de regrouper ces deux classes en une seule, nommée par exemple Autorisation. Cette classe s’accommoderai de trois attributs principaux : Autorisation (booléen permettant de renseigner l’autorisation ou non), Reserve (booléen permettant de renseigner la présence d’une réserve ou non), TypeReserve (renseignant la réserve en question si besoin est).
![Autorisation](https://github.com/cnigfr/structuration-reglement-urbanisme/assets/157821386/05441484-f61a-48bb-a803-a1eb8c9fab03)

**Comment by GT-CNIG-DDU** [comment]
Dans votre modélisation, comment traitez-vous une interdiction ?
Pouvez-vous donner, dans les deux cas (interdiction / autorisation), des exemples concrets de remplissage des attributs...

**Comment by Elise-DELACOTTE** [comment]
<img width="960" alt="0001" src="https://github.com/cnigfr/structuration-reglement-urbanisme/assets/157821386/4c6fc410-4e67-421c-bfcd-505f69c24e60">

**Comment by Elise-DELACOTTE** [comment]
<img width="960" alt="0002" src="https://github.com/cnigfr/structuration-reglement-urbanisme/assets/157821386/bc14d73a-98c0-4bfc-8d16-2a77c4a733ee">

**Comment by GT-CNIG-DDU** [comment]
Merci.
Les attributs pourraient être renommés : 

- `autorisation` => `type `(liste de valeurs "autorisation", "interdiction")
- `reserve `=> `existReserve` (booléen)
- `typeReserve `=> `reserve `(chaîne de caractères)

**Comment by mbrasebin** [comment]
A la base l'idée d'avoir 2 classes était pour distinguer les 2 premiers articles du PLU.

Dans mon habitude de modélisation, j'ai tendance à multiplier les classes pour les distinguer par les intitulés plutôt que de les fusionner et d'ajouter des attributs, mais pas d'objection particulière sinon.

**Comment by GT-CNIG-DDU** [comment]
De plus, une classe unique devrait porter un nom différent de `Autorisation`, car il est absolument contre-intuitif de mette des interdictions dans une classe qui porterait le nom de `Autorisation`.

**Comment by alisonlenain** [comment]
**Rajout attributs : 
- "existReserve (booléen) (existance de la présence d'une réserve) " 
- "reserve (CharacterString) (renseignant la réserve en question si besoin est)."
- type (liste de valeurs "autorisation", "interdiction")**

** Renommer la classe (elle devrait porter un nom différent de Autorisation)**

**Comment by alisonlenain** [comment]
Proposition de renommer cette classe en contrainte générale.

**Comment by GT-CNIG-DDU** [comment]
En attente du CR de la réunion SG6 du 18 avril... durant laquelle il avait été convenu de ne pas suivre la préconisation de l'équipe PPP et continuer à disposer de deux classes distinctes : "autorisation" et "interdiction".

**Comment by GT-CNIG-DDU** [comment]
En attente du CR de la réunion SG6 du 18 avril... durant laquelle il avait été acté de ne pas suivre la préconisation de l'équipe PPP (pour éviter des dénominations trop floues comme "OccupationUtilisatonSol" ou "Contrainte Générale") et de continuer à disposer de deux classes distinctes : "autorisation" et "interdiction".

**Comment by alisonlenain** [comment]
Le CR fera directement référence à l'issue. Il a été acté de renommer la classe Contrainte Générale lors de lors dernière réunion et on avait acté lors de la réunion en mars de fusionner ces deux classes. Je peux renvoyer les vidéos des dernières réunions si nécessaires

**Comment by alisonlenain** [comment]
Classes validées par les membres du SG6 (modification de l'attribut existReserve en existeReserve)
