### ISSUE TITLE
[PPP ESGT] Suggestion d'amélioration du MCD - Rajout classe Clôture

### ISSUE THREAD

**Issue by EliotBerthie** [cnigfr/structuration-reglement-urbanisme#23]
Il peut être intéressant d'ajouter les caractéristiques techniques quantifiables des clôtures, étant dans certains PLUs difficile à intégrer dans les classes d’objets. 
Nous proposons donc de créer une classe Clôture permettant de modéliser. Voici des exemples d'attributs pouvant être contenu dans la classe : 
- Hmax (hauteur maximale de la clôture) ;
- PerméabiliteMax (perméabilité maximale des clôtures dans les secteurs soumis à risques inondations) ;
- HmaxMurBahut (hauteur maximale des murs bahuts);
- Hmassif (hauteur de massif).

![cloture](https://github.com/cnigfr/structuration-reglement-urbanisme/assets/157822468/5fcb3f05-9783-4d36-b632-312031ab12d0)

**Comment by mbrasebin** [comment]
Est-ce qu'il n'y aurait pas lieu de préciser une liste de types de clotures autorisées ? 

Il y aurait aussi à ouvrir le dossier de l'article 11 du PLU sur les aspects extérieurs qui n'est pas trop traité dans le projet de standard (à faire plus tard). Ou certaines autres thématiques peuvent être modélisés : nombre d'arbres / matériaux autorisés dans une certaine limite.

Il y a quelques éléments ici : https://www.gridauh.fr/sites/default/files/u440/4a25008965128.pdf  à voir si l'on creuse

**Comment by alisonlenain** [comment]
Sera proposée lors de la prochaine réunion 08/03

**Comment by alisonlenain** [comment]
**Ok pour rajout la classe cloture. (Cela pourra entrainer l'ajout de nombreuses classes au modèle** = action AL regarder si d'autres éléments ne sont pas déjà modèlisés dans les contraintes et les conditions pour veiller à la cohérence du modèle). 

Buildzr ont choisi de prendre en compte les éléments impactants l'implantation (qui ne sont pas limitées à l'art 11) comme la longueur façade , les pentes toitures , la définition des attiques.

**Comment by alisonlenain** [comment]
Travail sur la modélisation de la classe Cloture est terminée. Pour la prise en compte des autres AspectExterieur cf issue #32
