### ISSUE TITLE
[PPP ESGT] Suggestions d'améliorations du MCD - Proposition d'ajout de la classe ImplantationBati_UF

### ISSUE THREAD

**Issue by Elise-DELACOTTE** [cnigfr/structuration-reglement-urbanisme#25]
Les PLUs de Preignan et de Pechbonnieu différencient dans leurs règlements les règles relatives à l’implantation des constructions par rapport aux voies et emprises publiques, mais aussi limites séparatives et des constructions les unes par rapport aux autres sur une même propriété. Si les deux premières sont modélisées dans la classe RetraitAlignement, nous avons estimé qu’il est nécessaire de faire la distinction sur les implantations des constructions au sein d’une unité foncière. Nous proposons donc par conséquent l’ajout de la classe **ImplantationBati_UF** (UF = Unité Foncière), constitué de deux attributs : _distance_ et _ParRapport_.
![ImplantationBati_UF](https://github.com/cnigfr/structuration-reglement-urbanisme/assets/157821386/5f402943-dd44-4780-a418-e0aa5505e1ce)

**Comment by mbrasebin** [comment]
Le champs référence de la classe mère RetraitAlignement peut prendre la valeur Batiment pour autre bâtiment de la parcelle. Pour moi, la définition d'une nouvelle classe n'est pas nécessaire

**Comment by GT-CNIG-DDU** [comment]
Je suis du même avis que @mbrasebin

**Comment by alisonlenain** [comment]
Proposition d'ajout de l'attribut "référence" dans la classe RetraitAlignement. La valeur batiment est déja inclue dans l'énumération "TypeReference". 

![image](https://github.com/cnigfr/structuration-reglement-urbanisme/assets/95492315/67407457-162f-486e-ac37-7070548a520e)
