### ISSUE TITLE
[PPP ESGT] Suggestions d'améliorations du MCD - Proposition de rajout de la classe TypeVoirie

### ISSUE THREAD

**Issue by Elise-DELACOTTE** [cnigfr/structuration-reglement-urbanisme#26]
Enfin nous avons considéré qu’il manquait une condition unitaire. Il s’agit d’une
classe permettant de préciser le type de voirie. Certaines règles d’implantation se faisant en
fonction du type et/ou de nom de voirie. La classe RouteBordante peut de prime abord
sembler convenir, mais cette classe considère d’autres règles en réalité puisqu’elle mentionne
une largeur de route. Or dans notre règle d’implantation, la largeur de la route ne nous
importe pas. Nous proposons donc la classe **TypeVoirie**, constitué d’un unique attribut,
_TypeVoirie,_ permettant de modéliser le type et/ou le nom de voirie concerné par la règle
d’alignement. 
![RetraitAlignement](https://github.com/cnigfr/structuration-reglement-urbanisme/assets/157821386/6cc85d03-1982-483f-ad2d-cbfd694443c0)

**Comment by mbrasebin** [comment]
A fusionner avec RouteBordante et garder l'intitulé TypeVoirie qui est peut être plus explicite

**Comment by alisonlenain** [comment]
Rajout de l'attribut TypeVoirie dans la classe VoirieBordante pour la prise en compte du type et/ou le nom de voirie concerné par la règle d’alignement.

**Comment by GT-CNIG-DDU** [comment]
A ce stade je ne visualise pas bien son contenu. S'agit-il d'une liste de valeurs ou d'un libellé libre, ou autre ?
Peut-on définir des exemples de remplissage ?

**Comment by GT-CNIG-DDU** [comment]
Je me réponds à moi-même : 
Le projet de standard prévoit une liste de valeurs : [Nationale, Régionale, Départementale] (liste à valider en SG6)
Mais du coup le nom de la voie n'apparait pas (?)

**Comment by alisonlenain** [comment]
Il y a bien un attribut pour renseigner le nom de la voie dans la classe VoirieBordante
