### ISSUE TITLE
Remarque sur catalogue d'objets vprojet_2023-11_Sous_Destinations

### ISSUE THREAD

**Issue by alisonlenain** [cnigfr/structuration-reglement-urbanisme#28]
Liste a créer par le SG6 car les sous destinations pas prises en compte dans le standard CNIG PLU car les sous destinations ne sont pas inclus dans le code de l’urbanisme. Dans standard PLU représenté par code à 2 chiffres."En lien avec l'issue #14 

Les valeurs actuelles de l’énumération destination sont : residentiel, commercial, logement social, activiteService, industrie, entrepot. 

Les destinations sont bien décrites dans le code de l'urbanisme ([article R151-8](https://www.legifrance.gouv.fr/codes/article_lc/LEGIARTI000041525837)) et codifiées dans le [standard PLU](https://cnig.gouv.fr/IMG/pdf/231220_standard_cnig_plu_v2024-01.pdf) cf DestinationType)
"logement" y figure, mais pas "logement social" => code 23 (et éventuellement d'autres codes ?) à créer dans cette liste de valeur pour les besoins du standard SRU niveau ?

Reprendre liste de ses destinations comprises dans le standard PLU et la compléter (notamment avec les exemples fournies par Yana) : 
Les contraintes d'emprise au sol et d'espaces verts peuvent devenir plus permissives sous réserve de respect d'une proportion minimale de logements sociaux ou de présence des commerces en RDC. La proportion sera calculée soit à l'échelle de l'ensemble de constructions nouvelles sur l'unité foncière, soit bâtiment par bâtiment (auquel cas il y aura deux poids deux mesures). La notion de destination principale / secondaire peut être utilisée en lieu et place d'une telle proportion.

Les normes de stationnement sont calculées à l'échelle de l'ensemble de constructions nouvelles sur l'unité foncière, par sousdestination plutôt que par destination, mais le niveau de précision reste variable. Le minimum est de pouvoir distinguer les logements privés et sociaux, les résidences étudiantes. Les logements peuvent être subdivisés par taille également, en maisons individuelles et logements collectifs, les commerces en commerces de gros et individuels. Au passage, le calcul de places se fera
-- soit par nb de logements
-- soit par nb de logements d'un certain type
-- soit par nb de logements d'une certaine surface de plancher
-- soit par tranche en m² de surface de plancher totale

Les autorisations / interdictions des articles 1 et 2 peuvent imposer, à toute la zone ou uniquement aux parcelles concernées par une PG (servitude de mixité sociale ou fonctionnelle), la présence ou l'absence des commerces au RDC, ainsi qu'une proportion minimale de logements sociaux, soit au sens large du terme, soit de type spécifique : PLAI, PLUS, PLS, PLI ...

**Comment by alisonlenain** [comment]
Ces propositions seront soumises à la prochaine réunion du 08/03

**Comment by GT-CNIG-DDU** [comment]
> Est ce que l'attribut destination : TypeDestination de la classe Type Batiment du standard CNIG SRU devrait reprendre également les sous destinations mentionnées dans le standard CNIG PLU ?

Si c'est possible, je dirais oui : autant prendre la même nomenclature afin qu'elle soit commune à PLU/CC et à SRU.
Avec (si j'ai bien compris) ajout d'un troisième niveau à DestinationType pour détailler par exemple Habitation / Logement

**Comment by alisonlenain** [comment]
D'accord, je te remercie pour ta rapide réponse. J'intègre les modifications et j'envoie la version actualisée du standard aujourd'hui

**Comment by GT-CNIG-DDU** [comment]
Ok. Ou bien utiliser les codes (10 à 99) plutôt que les libellés, comme le fait le standard PLU/CC ? _(à discuter...)_

**Comment by alisonlenain** [comment]
Remplacer les attributs TypdeDestination et TypeSousDestination par l'attribut DestinationType du Standard CNIG PLU avec la liste des codes définie dans le standard CNIG PLU.
Conserver l'attribut TypeLogement.

**Comment by alisonlenain** [comment]
Changement du type de données de l'attribut destinationType en characterString pour la prise en compte des codes du standard CNIG PLU
