### ISSUE TITLE
Classe TypeReference

### ISSUE THREAD

**Issue by mbrasebin** [cnigfr/structuration-reglement-urbanisme#29]
J'ouvre ce ticket pour parler de la classe TypeReference.

Elle est utilisée pour définir un type d'objet qui sera le support de mesures de distances. Ce type apparaît dans la notion de champs d'application et de retrait/alignement.  

La définition de cette référence permettra d'effectuer un test soit topologique (un objet est aligné avec un autre) soit géométrique (un objet se trouve à une distance de X m d'un autre).  

Dans le standard, il y a actuellement cet ensemble qui est décrit : 
![image](https://github.com/cnigfr/structuration-reglement-urbanisme/assets/10995312/9c88fc6f-619f-4d7d-9788-28b37cdae274)

- fond, limitelateral, voie/emprise publique désigne les limites sépratives de fond / latérale de parcelles et celles donnant sur la voirie ou les emprises publiques  ;
- bâtiment correspond aux bâtiments de la parcelle

Je me demandais si  :
- IntersectionTerrainVoirie : ne correspondait pas à la limite donnant sur la voirie ; 
- intersectionTerrainPg : je ne suis pas très sur de voir l'utilité de cela au regard des classes utilisant ce concept de TypeReference
- margeRecul : j'ai l'impression que c'est déjà le résultat de l'application d'une marge de recul à partir d'une référence ? 

J'aurai tendance à supprimer ces concepts là et à rajouter : 
- Pignon attenant
- Bâtiment attenant

**Comment by alisonlenain** [comment]
Action pour le 08/03 : 

Valider l'une des deux définitions proposées : 

Topologique : un objet est aligné avec un autre,
Géométrique : un objet se trouve à une distance de X m d'un autre

Suppression de la valeur :
Proposition de supprimer 
- margeRecul  
- IntersectionTerrainVoirie
-  intersectionTerrainPG

Rajout des valeurs : 
- Pignon attenant
- Bâtiment attenant

**Comment by alisonlenain** [comment]
J'ai indiqué les définitions pour Batiment et Pignon dans le glossaire. Est-il nécessaire d'ajouter des définitions pour Batiment attenant et Pignon attenant ?

**Comment by alisonlenain** [comment]
@mbrasebin est ce que tu aurais des définitions à proposer pour Batiment attenant et Pignon attenant s'il te plait ?

**Comment by alisonlenain** [comment]
Suppression des énumérants : 

margeRecul
IntersectionTerrainVoirie
intersectionTerrainPG

Rajout des valeurs  et les définir (@mbrasebin )

Pignon attenant
Bâtiment attenant

Yana souligne que la notion "voie" n'est pas claire dans le sens si on parle de la limite publique ou de l'axe de la voie ou de l'alignement opposé car il y a plusieurs points de références vis à vis d'une voie.

Proposition de remplacer "voie" par les trois limites (limite publique ou de l'axe de la voie ou de l'alignement opposé).

Cela pour concernait également la notion de retrait pour la notion de garabit opposé. 

Benjamin Aubry signale qu'il y a d'autres types de références qui peuvent etre prises en compte comme des éléments naturels (exemple un ruisseau) car ils ont des impacts en terme d'implantation. Proposition d'ajouter les éléments naturels dans cette liste.

**Comment by alisonlenain** [comment]
Proposition d'ajouter les éléments naturels dans cette liste : 

bergesCoursEau
fossesMeres
domainePublicFluvial

**Comment by GT-CNIG-DDU** [comment]
Pas d'opposition sur le principe de ces ajouts de valeurs, mais je me questionne : 
- qu'est-ce qu'une (ou des) FossesMeres ?
- la limite du domaine public fluvial n'étant, j'imagine, pas matérialisée sur le terrain, comment la prendre comme référence ?

**Comment by alisonlenain** [comment]
Supression de la valeur fossesMeres
