### ISSUE TITLE
Nommage des attibuts d'identifiants

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/structuration-reglement-urbanisme#30]
L'issue #11 spécifie la forme et le contenu des identifiants d'objets.

Proposition (mentionnée [issue 16](https://github.com/cnigfr/structuration-reglement-urbanisme/issues/16#issuecomment-1923991296)) que les attributs "identifiants" de chaque classe soit nommés : id\<nom de la classe ou un diminutif>
Par exemple : 
- id => IdRegle (en décidant - ou pas -  de renommer RegleStruture en Regle)
- id => IdCondition (ou idCdu)
- id => IdContrainte (ou idCtu)

etc.

**Comment by alisonlenain** [comment]
Validé lors de la dernière réunion. 
Une précision a été apportée, le nom des identifiants devraient commencer par une minuscule : 

id => idRegle (en décidant - ou pas - de renommer RegleStruture en Regle)
id => idCondition (ou idCdu)
id => idContrainte (ou idCtu)

**Comment by GT-CNIG-DDU** [comment]
Cette issue est indiquée comme "en cours" dans le CR du 11 juin, mais au vu du projet de standard v2024-08 elle semble maintenant résolue.
