### ISSUE TITLE
Simplifier le nom des classes d'objet

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/structuration-reglement-urbanisme#31]
Proposition de renommer la classe "RegleStructure" en "Regle" : ce nom est plus simple

De même ConditionUnitaire et ContrainteUnitaire pourraient être renommées : "Condition" et "Contrainte"

**Comment by alisonlenain** [comment]
A été évoqué lors de la dernière réunion et sera validé lors de la réunion du 18.04

**Comment by alisonlenain** [comment]
Modification intégrées dans le document du standard

**Comment by GT-CNIG-DDU** [comment]
Le projet de standard comporte encore des mentions à "ConditionUnitaire" et "ContrainteUnitaire"

**Comment by GT-CNIG-DDU** [comment]
Proposition : 
ConditionUnitaire => Condition
ContrainteUnitaire => Contrainte
ConditionUnitaireSpecifique => ConditionSpecifique
