### ISSUE TITLE
Classe Accollement Pignon Attenant

### ISSUE THREAD

**Issue by mbrasebin** [cnigfr/structuration-reglement-urbanisme#33]
Parfois le PLU peut interdire ou obliger la construction contre un mur pignon d'un bâtiment existant dans la parcelle voisine 

"la nouvelle construction doit s’implanter à l’alignement de la voie ou dans le prolongement d’éléments bâtis existants c’est‐à‐dire,
le plus souvent, en s’adossant aux pignons aveugles existants" (source : https://www.ville-guerande.fr/fileadmin/user_upload/AVAP/2-implantation-.pdf)

![Implantation et volumétrie-3](https://github.com/cnigfr/structuration-reglement-urbanisme/assets/10995312/aca6111a-1685-49e7-986a-9a7c2b8a5700)

Pour moi il s'agit d'un type d'alignement particulier qui s'applique aux pignons en attente soit de la parcelle en cours soit de la parcelle voisine.

Pour moi le plus simple serait de rajouter 2 références : pignon / pignonmitoyen

**Comment by GT-CNIG-DDU** [comment]
@alisonlenain avant de clore l'issue : où apparaissent ces références dans le projet de standard ?

**Comment by alisonlenain** [comment]
Ces valeurs sont inclues dans l'énumération "TypeRéférence" (La validation de cette notion +le choix du nom pour éviter la confusion ont été validés lors de la dernière réunion)
